---
title: "20230914-misc_adhoc_other-claims"
author: "Jared Garfinkel"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(plotly)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

### Read in data

```{r}
df = readxl::read_xlsx("./data/Claims.xlsx", sheet = "Claims") |> 
  janitor::clean_names()
mydf = df |> 
  mutate(month = month(date_of_service),
         year = year(date_of_service),
         day = day(date_of_service))
```

### Find the means

```{r}
head(df)

df |> 
  mutate(month = month(date_of_service),
         year = year(date_of_service),
         day = day(date_of_service)) |> 
  group_by(year, month) |> 
  summarize(sum = sum(amount)) |> 
  summarize(mean = mean(sum)) |>  #117, 160, 100
  summarize(mean = mean(mean)) # 126

125+45*3 # 260
125*3 # 375
100*3 # 300
```

### How frequently do I buy LIRR tickets?

```{r}
mydf |> 
  filter(str_detect(notes, "LIRR"),
         amount %in% c(-87.25, -91.50),
         date_of_service > mdy("06-30-2022")) |> 
  mutate(lead_date = lead(date_of_service),
         duration = as.numeric(difftime(date_of_service, lead_date, units = "days"))) 
  summarize(mean = mean(duration, na.rm=TRUE),
            sd = sd(duration, na.rm=TRUE))
```

### What do I pay for MTA rides?

```{r}
myplot = mydf |> 
  filter(str_detect(notes, "NYCT")) |> 
  group_by(year, month) |> 
  summarize(sum = sum(amount),
            yearmon = ymd(paste(year, month, "01", sep = "-"))) |> 
  filter(yearmon > ymd("2022-05-02")) |> 
  ggplot(aes(x = yearmon, y = sum)) +
  geom_point() +
  geom_smooth(method = "lm")

ggplotly(myplot)
```

